---
name: Bug report
about: Create a report to help us improve
title: ''
labels: 'bug'
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Run 'usb-device-monitor'
2. Connect/disconnect a USB device
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04, Arch Linux, Fedora 38]
 - Python version: [e.g. 3.8, 3.9, 3.10, 3.11]
 - GTK version: [e.g. 3.24.0]
 - Desktop environment: [e.g. GNOME, KDE, XFCE]

**Additional context**
Add any other context about the problem here.

**Debug output**
If you ran the application with debug output, please include it here:
```bash
python3 -u usb_device_monitor/main.py
```
